version: '3'

services:
  mdbook:
    container_name: mdbook
    image: peaceiris/mdbook:v0.4.7
    # image: peaceiris/mdbook:v0.x.x-rust
    stdin_open: true
    tty: true
    ports:
      - 4000:3000
      - 4001:3001
    volumes:
      - ${PWD}:/book
    command:
      - serve
      - --hostname
      - '0.0.0.0'